Repository woowasap/ASAP, pull requests merged in 2023-08, with the labels that each got.

#13 refactor: `gradle 세팅을 multi-module` 맞게 수정한다
  build.gradle
  gradle/jacoco.gradle
  gradle/junit.gradle
  gradle/lombok.gradle
  gradle/sonar.gradle
  gradle/spring.gradle
  lombok.config
  settings.gradle
  support/.gitignore
  support/build.gradle
  support/jacoco/.gitignore
  support/jacoco/build.gradle
Labels: ♻️ refactor

#14 refactor: `app 모듈을 추가`및 unit-test-ci에서 인수테스트를 제거
  .github/workflows/acceptancetest-analyze.yml
  .github/workflows/unittest-analyze.yml
  app/.gitignore
  app/build.gradle
  app/src/main/java/shop/woowasap/Application.java
  app/src/test/java/shop/woowasap/accept/.gitkeep
  settings.gradle
Labels: ♻️ refactor

#17 refactor: `core.entity` 모듈 생성
  app/build.gradle
  auth/auth-repository/build.gradle
  core/build.gradle
  core/entity/build.gradle
  core/entity/src/main/java/shop/woowasap/core/entity/.gitkeep
  settings.gradle
  shop/shop-repository/build.gradle
  src/main/java/shop/woowasap/asap/auth/domain/User.java
  src/main/java/shop/woowasap/asap/auth/repository/.gitkeep
  src/main/java/shop/woowasap/asap/auth/service/.gitkeep
  src/main/java/shop/woowasap/asap/payment/domain/.gitkeep
  src/main/java/shop/woowasap/asap/payment/repository/.gitkeep
  src/main/java/shop/woowasap/asap/payment/service/.gitkeep
  src/main/java/shop/woowasap/asap/shop/controller/.gitkeep
  src/main/java/shop/woowasap/asap/shop/core/.gitkeep
  src/main/java/shop/woowasap/asap/shop/domain/User.java
  src/main/java/shop/woowasap/asap/shop/domain/UserType.java
  src/main/java/shop/woowasap/asap/shop/repository/.gitkeep
  src/main/java/shop/woowasap/asap/shop/service/.gitkeep
Labels: ♻️ refactor

#19 refactor: coverage-exclude.asap 경로를 모듈에 맞게 수정
  coverage-exclude.asap
Labels: ♻️ refactor

#22 chore: `settings.gradle`의 rootProject.name 변경
  app/src/main/java/shop/woowasap/Application.java
  settings.gradle
Labels: 🍻 chore

#23 chore: `Infer analyze CI` 추가
  .github/workflows/infer-analyze.yml
  Dockerfile-Infer
Labels: 🍻 chore

#34 test: auth, shop `인수테스트 API supporter 추가`
  app/build.gradle
  app/src/test/java/shop/woowasap/accept/support/api/AuthApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
  app/src/test/java/shop/woowasap/mock/dto/LoginRequest.java
  app/src/test/java/shop/woowasap/mock/dto/RegisterProductRequest.java
  app/src/test/java/shop/woowasap/mock/dto/SignUpRequest.java
  app/src/test/java/shop/woowasap/mock/dto/UpdateProductRequest.java
Labels: ✅ test

#35 test: 인수테스트 템플릿 추가
  app/build.gradle
  app/src/test/java/shop/woowasap/BeanScanBaseLocation.java
  app/src/test/java/shop/woowasap/accept/.gitkeep
  app/src/test/java/shop/woowasap/accept/AcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/AuthApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/valid/AuthValidator.java
  app/src/test/java/shop/woowasap/accept/support/valid/HttpValidator.java
  app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
  app/src/test/java/shop/woowasap/mock/dto/LoginRequest.java
  app/src/test/java/shop/woowasap/mock/dto/ProductsResponse.java
  app/src/test/java/shop/woowasap/mock/dto/RegisterProductRequest.java
  app/src/test/java/shop/woowasap/mock/dto/SignUpRequest.java
  app/src/test/java/shop/woowasap/mock/dto/SignUpResponse.java
  app/src/test/java/shop/woowasap/mock/dto/UpdateProductRequest.java
Labels: ✅ test

#36 test: 회원가입 인수테스트 작성
  .github/workflows/infer-analyze.yml
  app/build.gradle
  app/src/test/java/shop/woowasap/BeanScanBaseLocation.java
  app/src/test/java/shop/woowasap/accept/.gitkeep
  app/src/test/java/shop/woowasap/accept/AcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/AuthAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/AuthApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/valid/AuthValidator.java
  app/src/test/java/shop/woowasap/accept/support/valid/HttpValidator.java
  app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
  app/src/test/java/shop/woowasap/mock/dto/LoginRequest.java
  app/src/test/java/shop/woowasap/mock/dto/ProductsResponse.java
  app/src/test/java/shop/woowasap/mock/dto/RegisterProductRequest.java
  app/src/test/java/shop/woowasap/mock/dto/SignUpRequest.java
  app/src/test/java/shop/woowasap/mock/dto/SignUpResponse.java
  app/src/test/java/shop/woowasap/mock/dto/UpdateProductRequest.java
Labels: ✅ test

#39 fix: Infer CI 에서 `accept test` 제외
  Dockerfile-Infer
Labels: 🐛 bug-fix

#37 test: 상품 등록 인수테스트 작성
  Dockerfile-Infer
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/product/ProductFixture.java
  app/src/test/java/shop/woowasap/accept/support/valid/HttpValidator.java
  app/src/test/java/shop/woowasap/mock/dto/LoginResponse.java
Labels: ✅ test

#40 test: 상품수정 인수테스트 작성
  Dockerfile-Infer
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/product/ProductFixture.java
  app/src/test/java/shop/woowasap/accept/support/valid/HttpValidator.java
  app/src/test/java/shop/woowasap/mock/dto/LoginResponse.java
Labels: ✅ test

#43 feat: 유저 도메인 생성
  .github/workflows/infer-analyze.yml
  Dockerfile-Infer
  auth/auth-domain/src/main/java/shop/woowasap/auth/domain/Password.java
  auth/auth-domain/src/main/java/shop/woowasap/auth/domain/User.java
  auth/auth-domain/src/main/java/shop/woowasap/auth/domain/UserId.java
  auth/auth-domain/src/main/java/shop/woowasap/auth/domain/exception/AuthDomainBaseException.java
  auth/auth-domain/src/main/java/shop/woowasap/auth/domain/exception/DuplicatedUserIdException.java
  auth/auth-domain/src/main/java/shop/woowasap/auth/domain/exception/PasswordValidateException.java
  auth/auth-domain/src/main/java/shop/woowasap/auth/domain/exception/UserIdValidateException.java
  auth/auth-domain/src/test/java/shop/woowasap/auth/domain/PasswordTest.java
  auth/auth-domain/src/test/java/shop/woowasap/auth/domain/UserIdTest.java
  auth/auth-domain/src/test/java/shop/woowasap/auth/domain/UserTest.java
Labels: ✨ feature

#45 feat: snowflake id generator 생성
  auth/auth-service/build.gradle
  core/id-gen/build.gradle
  core/id-gen/src/main/java/shop/woowasap/core/id/api/IdGenerator.java
  core/id-gen/src/main/java/shop/woowasap/core/id/snowflake/SnowflakeIdGenerator.java
  core/id-gen/src/test/java/shop/woowasap/core/id/snowflake/SnowflakeIdGeneratorTest.java
  settings.gradle
  shop/shop-service/build.gradle
Labels: ✨ feature

#41 feat: 상품 등록 관련 도메인 작성
  shop/shop-domain/build.gradle
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/Order.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/Product.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Description.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Name.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Price.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Product.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Quantity.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/exception/InvalidProductDescriptionException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/exception/InvalidProductNameException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/exception/InvalidProductPriceException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/exception/InvalidProductQuantityException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/exception/InvalidProductSaleTimeException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/exception/ProductException.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/product/DomainFixture.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/product/ProductTest.java
Labels: ✨ feature

#44 test: 상품 수정 인수테스트 수정 및 추가
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/valid/HttpValidator.java
Labels: ✅ test

#47 test: 특정 상품 조회 인수테스트를 작성한다
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/fixture/ProductDtoFixture.java
  app/src/test/java/shop/woowasap/accept/support/valid/HttpValidator.java
  app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
  app/src/test/java/shop/woowasap/mock/dto/ProductResponse.java
Labels: ✅ test

#49 feat: productId로 Product 조회 기능 추가
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/fixture/ProductDtoFixture.java
  app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
  app/src/test/java/shop/woowasap/mock/dto/ProductResponse.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/Product.java
  shop/shop-service/build.gradle
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/dto/ProductResponse.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/exception/CannotFindProductException.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/repository/ProductRepository.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/ProductFixture.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/valid/ProductValidator.java
Labels: ✨ feature

#50 fix: ShopValidator의 softAssertions 수정
  app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
Labels: 🐛 bug-fix

#51 feat: 상품 수정 서비스 구현
  shop/shop-domain/build.gradle
  shop/shop-domain/src/test/java/shop/woowasap/domain/product/ProductTest.java
  shop/shop-domain/src/test/java/shop/woowasap/domain/support/DomainFixture.java
  shop/shop-domain/src/test/java/shop/woowasap/domain/support/ProductFixture.java
  shop/shop-domain/src/test/java/shop/woowasap/domain/support/ProductValidator.java
  shop/shop-service/build.gradle
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/exception/UpdateProductException.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/repository/ProductRepository.java
  shop/shop-service/src/test/java/shop/woowasap/service/ProductServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/service/support/DomainFixture.java
  shop/shop-service/src/test/java/shop/woowasap/service/support/ProductFixture.java
Labels: ✨ feature

#53 feat: 상품 등록 컨트롤러 구현
  coverage-exclude.asap
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/.gitkeep
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java
Labels: ✨ feature

#42 feat: 상품 수정 controller 구현
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/product/ProductFixture.java
  app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
  coverage-exclude.asap
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/.gitkeep
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/Product.java
  shop/shop-domain/src/test/java/shop/woowasap/domain/product/ProductTest.java
  shop/shop-domain/src/test/java/shop/woowasap/domain/support/ProductFixture.java
  shop/shop-domain/src/test/java/shop/woowasap/domain/support/ProductValidator.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/.gitkeep
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/dto/UpdateProductRequest.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/repository/ProductRepository.java
  shop/shop-service/src/test/java/shop/woowasap/service/ProductServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/service/support/ProductFixture.java
Labels: ✨ feature

#64 fix: 상품 수정 기능 admin 추가 및 인가 test 제거
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java
Labels: 🐛 bug-fix

#68 chore: `Infer CI` 가 main, develop release PR 에서만 수행되도록 수정
  .github/workflows/infer-analyze.yml
Labels: 🍻 chore

#75 test: 특정 상품 조회 인수테스트를 추가한다
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/fixture/ProductFixture.java
  app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/api/response/ProductResponse.java
Labels: ✅ test

#77 test: 어드민 상품 전체 조회 인수테스트 작성
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/product/ProductFixture.java
  app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
  app/src/test/java/shop/woowasap/mock/dto/ProductsResponse.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductAdminController.java
Labels: ✅ test

#78 feat: `/products/{product-id}` API handler 추가
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductAdminController.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java
Labels: ✨ feature

#81 feat: 어드민 상품 목록 조회 서비스 구현
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/product/ProductFixture.java
  app/src/test/java/shop/woowasap/accept/support/fixture/ProductFixture.java
  app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/api/ProductUseCase.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/api/response/ProductsResponse.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/spi/ProductRepository.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/spi/response/ProductsPaginationResponse.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockProductRepository.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/mapper/ProductMapper.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/ProductFixture.java
Labels: ✨ feature

#80 test: 상품 전체 조회 인수테스트
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/fixture/ProductFixture.java
  app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
Labels: ✅ test

#82 feat: 상품 전체 조회 서비스 구현
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/fixture/ProductFixture.java
  app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/api/ProductUseCase.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/api/response/ProductsResponse.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/spi/ProductRepository.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/spi/response/ProductsPaginationResponse.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockProductRepository.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/ProductFixture.java
Labels: ✨ feature

#84 feat: 상품 전체 조회 컨트롤러를 구현한다
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductAdminController.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java
Labels: ✨ feature

#85 feat: 상품 전체 조회 - 어드민
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/product/ProductFixture.java
  app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/fixture/ProductFixture.java
  app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
  app/src/test/java/shop/woowasap/mock/dto/ProductsResponse.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductAdminController.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/api/ProductUseCase.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/api/response/ProductsResponse.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/spi/ProductRepository.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/spi/response/ProductsPaginationResponse.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockProductRepository.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/mapper/ProductMapper.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/ProductFixture.java
Labels: ✨ feature

#88 feat: 상품 상세 조회 기능 개발
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/fixture/ProductFixture.java
  app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductAdminController.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/api/ProductUseCase.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/api/response/ProductResponse.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/mapper/ProductMapper.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/DomainFixture.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/ProductDtoFixture.java
Labels: ✨ feature

#89 test: 어드민 상품 상세 조회 인수테스트 작성
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
Labels: ✅ test

#90 feat: 어드민 상품 상세 조회 서비스 구현
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/api/ProductUseCase.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/spi/ProductRepository.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockProductRepository.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java
Labels: ✨ feature

#91 feat: 어드민 상품 상세 조회 컨트롤러 구현
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductAdminController.java
Labels: ✨ feature

#92 feat: 상품 상세 조회 - 어드민
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductAdminController.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/api/ProductUseCase.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/spi/ProductRepository.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockProductRepository.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java
Labels: ✨ feature

#93 test: 상품 구매 인수테스트 추가
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/OrderApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/valid/OrderValidator.java
  app/src/test/java/shop/woowasap/mock/dto/OrderProductRequest.java
  settings.gradle
Labels: ✅ test

#87 feat: 회원 가입 컨트롤러
  app/build.gradle
  app/src/test/java/shop/woowasap/accept/AuthAcceptanceTest.java
  auth/auth-controller/build.gradle
  auth/auth-controller/src/main/java/shop/woowasap/auth/controller/.gitkeep
  auth/auth-controller/src/main/java/shop/woowasap/auth/controller/AuthController.java
  auth/auth-controller/src/main/java/shop/woowasap/auth/controller/request/SignUpRequest.java
  auth/auth-domain/src/main/java/shop/woowasap/auth/domain/in/response/UserResponse.java
  auth/auth-infra/build.gradle
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/JwtTokenProvider.java
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/configuration/WebSecurityConfiguration.java
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/filter/JwtTokenAuthFilter.java
  auth/auth-service/src/main/java/shop/woowasap/auth/service/configuration/PasswordEncoderConfiguration.java
  coverage-exclude.asap
  settings.gradle
Labels: ✨ feature

#97 feat: 로그인 인수테스트 추가
  app/src/test/java/shop/woowasap/accept/AuthAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/AuthApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/valid/AuthValidator.java
  app/src/test/java/shop/woowasap/mock/dto/SignUpRequest.java
Labels: ✨ feature

#98 feat: Order 모듈의 도메인 생성
  order/order-domain/src/main/java/shop/woowasap/order/domain/Order.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/OrderProduct.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/exception/.gitkeep
  order/order-domain/src/main/java/shop/woowasap/order/domain/exception/InvalidOrderProductException.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/exception/InvalidPriceException.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/exception/InvalidQuantityException.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/.gitkeep
  order/order-domain/src/main/java/shop/woowasap/order/domain/spi/.gitkeep
  order/order-domain/src/test/java/shop/woowasap/order/domain/OrderProductTest.java
  order/order-domain/src/test/java/shop/woowasap/order/domain/OrderTest.java
  order/order-domain/src/test/java/shop/woowasap/order/domain/support/fixture/OrderFixture.java
  order/order-domain/src/test/java/shop/woowasap/order/domain/support/fixture/OrderProductFixture.java
Labels: ✨ feature

#102 test: 장바구니 상품 조회 인수테스트 작성
  app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/CartApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/fixture/CartFixture.java
  app/src/test/java/shop/woowasap/accept/support/valid/CartValidator.java
  app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
Labels: ✅ test

#101 feat: 상품 단일 구매 서비스 추가
  .gitignore
  app/src/test/java/shop/woowasap/accept/support/api/OrderApiSupporter.java
  app/src/test/java/shop/woowasap/mock/dto/OrderProductRequest.java
  coverage-exclude.asap
  order/order-domain/src/main/java/shop/woowasap/order/domain/Order.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/OrderProduct.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/exception/DoesNotOrderedException.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/exception/InvalidProductSaleTimeException.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/exception/InvalidQuantityException.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/.gitkeep
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderUseCase.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/request/OrderProductRequest.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/OrderRepository.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/Payment.java
  order/order-domain/src/test/java/shop/woowasap/order/domain/OrderProductTest.java
  order/order-domain/src/test/java/shop/woowasap/order/domain/support/fixture/OrderFixture.java
  order/order-domain/src/test/java/shop/woowasap/order/domain/support/fixture/OrderProductFixture.java
  order/order-service/build.gradle
  order/order-service/src/main/java/shop/woowasap/order/service/.gitkeep
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
  order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/ProductFixture.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/api/ProductConnector.java
Labels: ✨ feature

#103 test: 장바구니 상품 추가 인수테스트 작성
  app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/CartApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/fixture/CartFixture.java
  app/src/test/java/shop/woowasap/accept/support/valid/CartValidator.java
Labels: ✅ test

#105 feat: `POST /v1/orders/products/{product-id}` handler 추가
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/OrderApiSupporter.java
  app/src/test/java/shop/woowasap/mock/dto/OrderProductRequest.java
  coverage-exclude.asap
  order/order-controller/build.gradle
  order/order-controller/src/main/java/shop/woowasap/order/controller/.gitkeep
  order/order-controller/src/main/java/shop/woowasap/order/controller/OrderController.java
  order/order-controller/src/main/java/shop/woowasap/order/controller/request/OrderProductQuantityRequest.java
  settings.gradle
Labels: ✨ feature

#106 feat: 0~1초 뒤 성공을 반환하는 RandomOrderPayment 생성
  coverage-exclude.asap
  order/order-infra/build.gradle
  order/order-infra/src/main/java/shop/woowasap/order/payment/random/RandomOrderPayment.java
  settings.gradle
Labels: ✨ feature

#107 feat: ProductConnectorService 구현
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/app/api/ProductConnector.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductConnectorService.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductConnectorServiceTest.java
Labels: ✨ feature

#109 feat: 상품 바로 구매
  app/build.gradle
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/OrderApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/valid/OrderValidator.java
  app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
  coverage-exclude.asap
  order/order-controller/build.gradle
  order/order-controller/src/main/java/shop/woowasap/order/controller/.gitkeep
  order/order-controller/src/main/java/shop/woowasap/order/controller/OrderController.java
  order/order-controller/src/main/java/shop/woowasap/order/controller/request/OrderProductQuantityRequest.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/Order.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/OrderProduct.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/api/.gitkeep
  order/order-domain/src/main/java/shop/woowasap/order/domain/exception/.gitkeep
  order/order-domain/src/main/java/shop/woowasap/order/domain/exception/DoesNotFindProductException.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/exception/DoesNotOrderedException.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/exception/InvalidOrderProductException.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/exception/InvalidPriceException.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/exception/InvalidProductSaleTimeException.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/exception/InvalidQuantityException.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderUseCase.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/request/OrderProductRequest.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/OrderRepository.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/Payment.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/spi/.gitkeep
  order/order-domain/src/test/java/shop/woowasap/order/domain/OrderProductTest.java
  order/order-domain/src/test/java/shop/woowasap/order/domain/OrderTest.java
  order/order-domain/src/test/java/shop/woowasap/order/domain/support/fixture/OrderFixture.java
  order/order-domain/src/test/java/shop/woowasap/order/domain/support/fixture/OrderProductFixture.java
  order/order-infra/build.gradle
  order/order-infra/src/main/java/shop/woowasap/order/payment/random/RandomOrderPayment.java
  order/order-repository/src/main/java/shop/woowasap/order/repository/.gitkeep
  order/order-repository/src/main/java/shop/woowasap/order/repository/MockOrderRepository.java
  order/order-service/build.gradle
  order/order-service/src/main/java/shop/woowasap/order/service/.gitkeep
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
  order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/ProductFixture.java
  settings.gradle
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/api/product/ProductConnector.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockProductRepository.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductConnectorService.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductConnectorServiceTest.java
Labels: ✨ feature

#110 test: 구매내역 전체 조회 인수테스트 생성
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/OrderApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/valid/OrderValidator.java
  app/src/test/java/shop/woowasap/mock/dto/OrderProductResponse.java
  app/src/test/java/shop/woowasap/mock/dto/OrderResponse.java
  app/src/test/java/shop/woowasap/mock/dto/OrdersResponse.java
  app/src/test/java/shop/woowasap/mock/dto/ProductsResponse.java
Labels: ✅ test

#111 feat: Order 도메인에 createdAt 추가
  order/order-domain/src/main/java/shop/woowasap/order/domain/Order.java
  order/order-domain/src/test/java/shop/woowasap/order/domain/OrderTest.java
Labels: ✨ feature

#113 feat: OrderService.getOrderByUserId 추가
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/valid/OrderValidator.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderUseCase.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/OrderProductResponse.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/OrderResponse.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/OrdersResponse.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/OrderRepository.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/response/OrdersPaginationResponse.java
  order/order-repository/src/main/java/shop/woowasap/order/repository/MockOrderRepository.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
  order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderDtoFixture.java
  order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderFixture.java
  order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderProductFixture.java
Labels: ✨ feature

#115 feat: `/v1/orders?page&size` handler 추가
  order/order-controller/src/main/java/shop/woowasap/order/controller/OrderController.java
Labels: ✨ feature

#114 feat: MockOrderRepository.findAllOrderByUserId 구현
  order/order-repository/src/main/java/shop/woowasap/order/repository/MockOrderRepository.java
Labels: ✨ feature

#116 feat: 구매내역 전체 조회
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/OrderApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/valid/OrderValidator.java
  app/src/test/java/shop/woowasap/mock/dto/ProductsResponse.java
  order/order-controller/src/main/java/shop/woowasap/order/controller/OrderController.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/Order.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderUseCase.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/OrderProductResponse.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/OrderResponse.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/OrdersResponse.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/OrderRepository.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/response/OrdersPaginationResponse.java
  order/order-domain/src/test/java/shop/woowasap/order/domain/OrderTest.java
  order/order-repository/src/main/java/shop/woowasap/order/repository/MockOrderRepository.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
  order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderDtoFixture.java
  order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderFixture.java
  order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderProductFixture.java
Labels: ✨ feature

#117 test: 특정 Order 조회 인수테스트 추가
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/OrderApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/valid/OrderValidator.java
  app/src/test/java/shop/woowasap/mock/dto/DetailOrderProductResponse.java
  app/src/test/java/shop/woowasap/mock/dto/DetailOrderResponse.java
Labels: ✅ test

#118 feat: 주문 내역 상세 조회 서비스 추가
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/valid/OrderValidator.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/exception/DoesNotFindOrderException.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderUseCase.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/DetailOrderProductResponse.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/DetailOrderResponse.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/OrderRepository.java
  order/order-repository/src/main/java/shop/woowasap/order/repository/MockOrderRepository.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
  order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderDtoFixture.java
Labels: ✨ feature

#121 feat: MockOrderRepository 구현
  order/order-repository/src/main/java/shop/woowasap/order/repository/MockOrderRepository.java
Labels: ✨ feature

#123 feat: 구매내역 상세조회
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/OrderApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/valid/OrderValidator.java
  order/order-controller/src/main/java/shop/woowasap/order/controller/OrderController.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/exception/DoesNotFindOrderException.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderUseCase.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/DetailOrderProductResponse.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/DetailOrderResponse.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/OrderRepository.java
  order/order-repository/src/main/java/shop/woowasap/order/repository/MockOrderRepository.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
  order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderDtoFixture.java
Labels: ✨ feature

#112 feat: 장바구니 상품 조회 서비스 구현
  coverage-exclude.asap
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/Cart.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/CartProduct.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/CartProductQuantity.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/spi/CartRepository.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockCartRepository.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/CartService.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/mapper/CartMapper.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/CartServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/CartFixture.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/DomainFixture.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/ProductFixture.java
Labels: ✨ feature

#124 refactor: `GET /v1/orders` API 응답 body 변경
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/OrderProduct.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/OrderProductResponse.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/OrderResponse.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
  order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderDtoFixture.java
Labels: ♻️ refactor

#125 feat: 장바구니 상품 조회 컨트롤러
  app/src/test/java/shop/woowasap/accept/support/valid/CartValidator.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/CartController.java
Labels: ✨ feature

#126 feat: 장바구니 상품 등록 서비스 기능 구현
  app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java
  coverage-exclude.asap
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/Cart.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/CartProduct.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/CartProductQuantity.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/Quantity.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/CartException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/InvalidCartProductQuantityException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/spi/CartRepository.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartProductTest.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartTest.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/support/CartFixture.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/CartService.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/CartServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/CartFixture.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/DomainFixture.java
Labels: ✨ feature

#128 feat: 장바구니 상품 등록 컨트롤러 구현
  app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/CartController.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/spi/CartRepository.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockCartRepository.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/CartService.java
Labels: ✨ feature

#129 feat: 장바구니 상품 등록 기능 구현
  app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/CartApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/fixture/CartFixture.java
  app/src/test/java/shop/woowasap/accept/support/valid/CartValidator.java
  coverage-exclude.asap
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/CartController.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/Cart.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/CartProduct.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/CartProductQuantity.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/Quantity.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/CartException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/InvalidCartProductQuantityException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/spi/CartRepository.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartProductTest.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartTest.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/support/CartFixture.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockCartRepository.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/CartService.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/CartServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/CartFixture.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/DomainFixture.java
Labels: ✨ feature

#131 test: `/v1/oreders/carts/{cart-id}` 인수테스트 추가
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/OrderApiSupporter.java
  app/src/test/java/shop/woowasap/mock/dto/ProductsResponse.java
Labels: ✅ test

#130 test: 장바구니 상품 제거 기능 인수테스트 작성
  app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java
Labels: ✅ test

#133 feat: 장바구니 상품 제거 도메인
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/Cart.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/CartProduct.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/CannotFindProductInCartException.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartTest.java
Labels: ✨ feature

#132 feat: 장바구니의 상품 주문 서비스 추가
  order/order-domain/src/main/java/shop/woowasap/order/domain/exception/DoesNotFindCartException.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderUseCase.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
  order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/CartFixture.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/api/cart/CartConnector.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/CartConnectorService.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/CartConnectorServiceTest.java
Labels: ✨ feature

#135 test: 장바구니 상품 수량 수정 인수테스트 작성
  app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java
Labels: ✅ test

#136 feat: 장바구니 상품 구매 기능 추가
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/OrderApiSupporter.java
  app/src/test/java/shop/woowasap/mock/dto/ProductsResponse.java
  order/order-controller/src/main/java/shop/woowasap/order/controller/OrderController.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/exception/DoesNotFindCartException.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderUseCase.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
  order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/CartFixture.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/api/cart/CartConnector.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockCartRepository.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/CartConnectorService.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/CartConnectorServiceTest.java
Labels: ✨ feature

#137 feat: 장바구니 상품 수량 수정 도메인 기능 구현
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/Cart.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/CartProduct.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/NotExistsCartProductException.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartProductTest.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartTest.java
Labels: ✨ feature

#138 feat: 장바구니 상품 제거 서비스 구현
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/spi/CartRepository.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockCartRepository.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/CartService.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/CartServiceTest.java
Labels: ✨ feature

#140 feat: 장바구니 상품 제거 컨트롤러 구현
  app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/CartApiSupporter.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/CartController.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/api/cart/CartUseCase.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockCartRepository.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockProductRepository.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/CartService.java
Labels: ✨ feature

#142 feat: 장바구니 상품 수량 수정 컨트롤러 구현
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/CartController.java
Labels: ✨ feature

#148 feat: Product Entity 기능 구현
  coverage-exclude.asap
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/entity/ProductEntity.java
Labels: ✨ feature

#149 feat: 로그인 서비스 및 토큰 프로바이더 구현
  app/src/main/java/shop/woowasap/configuration/TimeConfiguration.java
  app/src/main/resources/application.yml
  auth/auth-domain/src/main/java/shop/woowasap/auth/domain/UserType.java
  auth/auth-domain/src/main/java/shop/woowasap/auth/domain/Username.java
  auth/auth-domain/src/main/java/shop/woowasap/auth/domain/exception/LoginFailException.java
  auth/auth-domain/src/main/java/shop/woowasap/auth/domain/in/TokenProvider.java
  auth/auth-domain/src/main/java/shop/woowasap/auth/domain/in/UserUseCase.java
  auth/auth-domain/src/main/java/shop/woowasap/auth/domain/in/response/LoginResponse.java
  auth/auth-domain/src/main/java/shop/woowasap/auth/domain/in/response/UserResponse.java
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/AuthenticationProvider.java
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/JwtTokenProvider.java
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/configuration/WebSecurityConfiguration.java
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/filter/JwtTokenAuthFilter.java
  auth/auth-infra/src/test/java/shop/woowasap/auth/infra/AuthenticationProviderTest.java
  auth/auth-infra/src/test/java/shop/woowasap/auth/infra/JwtTokenProviderTest.java
  auth/auth-infra/src/test/resources/application.yml
  auth/auth-service/src/main/java/shop/woowasap/auth/service/AuthService.java
  auth/auth-service/src/test/java/shop/woowasap/auth/service/AuthServiceTest.java
  coverage-exclude.asap
Labels: ✨ feature

#153 feat: Product repository 기능 구현
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/ProductRepositoryImpl.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/jpa/ProductJpaRepository.java
Labels: ✨ feature

#156 feat: Cart Entity 기능 구현
  app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/fixture/ProductFixture.java
  app/src/test/resources/application.yml
  coverage-exclude.asap
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockProductRepository.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/ProductRepositoryImpl.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/entity/CartEntity.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/entity/CartProductEntity.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/entity/ProductEntity.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/jpa/ProductJpaRepository.java
Labels: ✨ feature

#161 refactor: `OrderProduct` 도메인에 name 필드 추가
  coverage-exclude.asap
  order/order-domain/src/main/java/shop/woowasap/order/domain/OrderProduct.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/exception/BlankProductNameException.java
  order/order-domain/src/test/java/shop/woowasap/order/domain/OrderProductTest.java
  order/order-domain/src/test/java/shop/woowasap/order/domain/support/fixture/OrderProductFixture.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
  order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderProductFixture.java
Labels: ♻️ refactor

#162 feat: CartRepository 기능 구현
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/CartRepositoryImpl.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/entity/CartEntity.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/jpa/CartJpaRepository.java
  shop/shop-repository/src/test/java/shop/woowasap/BeanScanBaseLocation.java
  shop/shop-repository/src/test/java/shop/woowasap/shop/repository/CartRepositoryImplTest.java
Labels: ✨ feature

#163 feat: Jpa 사용하는 OrderRepository 생성
  coverage-exclude.asap
  order/order-domain/src/main/java/shop/woowasap/order/domain/Order.java
  order/order-repository/src/main/java/shop/woowasap/order/repository/MockOrderRepository.java
  order/order-repository/src/main/java/shop/woowasap/order/repository/OrderRepositoryImpl.java
  order/order-repository/src/main/java/shop/woowasap/order/repository/entity/BaseEntity.java
  order/order-repository/src/main/java/shop/woowasap/order/repository/entity/OrderEntity.java
  order/order-repository/src/main/java/shop/woowasap/order/repository/entity/OrderProductEntity.java
  order/order-repository/src/main/java/shop/woowasap/order/repository/jpa/OrderJpaRepository.java
  order/order-repository/src/test/java/shop/woowasap/order/BeanScanBaseLocation.java
  order/order-repository/src/test/java/shop/woowasap/order/repository/OrderRepositoryImplTest.java
  order/order-repository/src/test/java/shop/woowasap/order/repository/support/OrderFixture.java
  order/order-repository/src/test/java/shop/woowasap/order/repository/support/OrderProductFixture.java
Labels: ✨ feature

#164 feat: 인수테스트용 어드민 계정 추가
  app/src/test/java/shop/woowasap/accept/AcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/AcceptanceTestConfiguration.java
  app/src/test/java/shop/woowasap/accept/support/api/AuthApiSupporter.java
  auth/auth-repository/src/main/java/shop/woowasap/auth/repository/entity/UserEntity.java
Labels: ✨ feature

#166 feat: 유저 Entitiy 및 레포지토리 구현
  app/src/test/java/shop/woowasap/accept/AcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/AcceptanceTestConfiguration.java
  app/src/test/java/shop/woowasap/accept/support/api/AuthApiSupporter.java
  app/src/test/resources/application.yml
  auth/auth-repository/src/main/java/shop/woowasap/auth/repository/MemoryUserRepository.java
  auth/auth-repository/src/main/java/shop/woowasap/auth/repository/UserEntityMapper.java
  auth/auth-repository/src/main/java/shop/woowasap/auth/repository/UserRepositoryImpl.java
  auth/auth-repository/src/main/java/shop/woowasap/auth/repository/entity/BaseEntity.java
  auth/auth-repository/src/main/java/shop/woowasap/auth/repository/entity/UserEntity.java
  auth/auth-repository/src/main/java/shop/woowasap/auth/repository/entity/UserEntityType.java
  auth/auth-repository/src/main/java/shop/woowasap/auth/repository/jpa/UserJpaRepository.java
  auth/auth-repository/src/test/java/shop/woowasap/BeanScanBaseLocation.java
  auth/auth-repository/src/test/java/shop/woowasap/auth/repository/UserRepositoryImplTest.java
Labels: ✨ feature

#169 test: Cart 인수테스트 수정
  app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/CartRepositoryImpl.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/MockCartRepository.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/entity/CartEntity.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/CartService.java
Labels: ✅ test

#170 feat: AuthArgumentResolver 추가
  app/src/test/java/shop/woowasap/accept/support/api/AuthApiSupporter.java
  auth/auth-domain/src/main/java/shop/woowasap/auth/domain/in/LoginUser.java
  auth/auth-domain/src/main/java/shop/woowasap/auth/domain/in/TokenProvider.java
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/AuthenticationProvider.java
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/JwtTokenProvider.java
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/configuration/WebConfiguration.java
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/resolver/AuthArgumentResolver.java
  auth/auth-infra/src/test/java/shop/woowasap/auth/infra/AuthenticationProviderTest.java
  auth/auth-infra/src/test/java/shop/woowasap/auth/infra/JwtTokenProviderTest.java
Labels: ✨ feature

#171 feat: 유저 아이디 ArgumentResolver 추가
  app/src/test/java/shop/woowasap/accept/support/api/AuthApiSupporter.java
  auth/auth-domain/src/main/java/shop/woowasap/auth/domain/in/LoginUser.java
  auth/auth-domain/src/main/java/shop/woowasap/auth/domain/in/TokenProvider.java
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/AuthenticationProvider.java
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/JwtTokenProvider.java
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/configuration/WebConfiguration.java
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/resolver/AuthArgumentResolver.java
  auth/auth-infra/src/test/java/shop/woowasap/auth/infra/AuthenticationProviderTest.java
  auth/auth-infra/src/test/java/shop/woowasap/auth/infra/JwtTokenProviderTest.java
Labels: ✨ feature

#174 chore: sonarcloud 가 develop에 push됐을때도 수행되도록 수정
  .github/workflows/acceptancetest-analyze.yml
Labels: 🍻 chore

#189 refactor: package 구조 `api -> in`, `spi -> out` 수정
  app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/product/ProductFixture.java
  app/src/test/java/shop/woowasap/accept/support/api/CartApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/api/ShopApiSupporter.java
  app/src/test/java/shop/woowasap/accept/support/fixture/CartFixture.java
  app/src/test/java/shop/woowasap/accept/support/fixture/ProductFixture.java
  app/src/test/java/shop/woowasap/accept/support/valid/CartValidator.java
  app/src/test/java/shop/woowasap/accept/support/valid/ShopValidator.java
  auth/auth-domain/src/test/java/shop/woowasap/auth/domain/UserTest.java
  auth/auth-domain/src/test/java/shop/woowasap/auth/domain/UsernameTest.java
  coverage-exclude.asap
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/CartController.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductAdminController.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/cart/CartConnector.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/cart/CartUseCase.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/cart/request/AddCartProductRequest.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/cart/request/UpdateCartProductRequest.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/cart/response/CartProductResponse.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/cart/response/CartResponse.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/product/ProductConnector.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/product/ProductUseCase.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/product/request/RegisterProductRequest.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/product/request/UpdateProductRequest.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/product/response/ProductDetailsResponse.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/product/response/ProductResponse.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/product/response/ProductsResponse.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/out/CartRepository.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/out/ProductRepository.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/out/response/ProductsPaginationResponse.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/CartRepositoryImpl.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/ProductRepositoryImpl.java
  shop/shop-repository/src/test/java/shop/woowasap/shop/repository/ProductRepositoryImplTest.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/CartConnectorService.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/CartService.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductConnectorService.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/mapper/CartMapper.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/mapper/ProductMapper.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/CartConnectorServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/CartServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductConnectorServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/CartFixture.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/ProductDtoFixture.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/ProductFixture.java
Labels: ♻️ refactor

#192 feat: 주문 성공시 상품 재고 감소 기능 추가
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/product/ProductConnector.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/out/ProductRepository.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/ProductRepositoryImpl.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/jpa/ProductJpaRepository.java
  shop/shop-repository/src/test/java/shop/woowasap/shop/repository/ProductRepositoryImplTest.java
  shop/shop-repository/src/test/java/shop/woowasap/shop/repository/support/ProductFixture.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductConnectorService.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductConnectorServiceTest.java
Labels: ✨ feature

#195 feat: `Payment, Stock Event` 정의
  app/build.gradle
  coverage-exclude.asap
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderConnector.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/Payment.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/event/PayFailEvent.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/event/PaySuccessEvent.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/event/StockFailEvent.java
  order/order-infra/build.gradle
  order/order-infra/src/main/java/shop/woowasap/order/payment/random/RandomOrderPayment.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
  payment/payment-domain/src/main/java/shop/woowasap/payment/domain/in/PaymentUseCase.java
  payment/payment-domain/src/main/java/shop/woowasap/payment/domain/out/.gitkeep
  settings.gradle
Labels: ✨ feature

#197 refactor: 주문성공시 OrderIdResponse와 Ok를 반환하도록 수정
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/valid/OrderValidator.java
  order/order-controller/src/main/java/shop/woowasap/order/controller/OrderController.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderUseCase.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/OrderIdResponse.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
Labels: ♻️ refactor

#199 refactor: Domain 과 Entity 에 주문의 상태 추가
  order/order-domain/src/main/java/shop/woowasap/order/domain/Order.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/OrderType.java
  order/order-domain/src/test/java/shop/woowasap/order/domain/OrderTest.java
  order/order-repository/src/main/java/shop/woowasap/order/repository/entity/OrderEntity.java
  order/order-repository/src/main/java/shop/woowasap/order/repository/entity/OrderEntityType.java
Labels: ♻️ refactor

#198 feat: Product 전체 조회를 startTime 기준으로 정렬
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/ProductRepositoryImpl.java
  shop/shop-repository/src/test/java/shop/woowasap/shop/repository/ProductRepositoryImplTest.java
Labels: ✨ feature

#200 feat: Product 상세 조회 시, 판매가 끝난 Product 일 경우 예외 발생
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/SaleEndedProductException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/out/ProductRepository.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Product.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/product/ProductTest.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/ProductRepositoryImpl.java
  shop/shop-repository/src/test/java/shop/woowasap/shop/repository/ProductRepositoryImplTest.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java
Labels: ✨ feature

#201 feat: `OrderEventService` 생성
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderEventConsumer.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/event/PayFailEvent.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/event/PaySuccessEvent.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/event/PayFailEvent.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/event/StockSuccessEvent.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderEventService.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderEventServiceTest.java
Labels: ✨ feature

#204 refactor: 주문 기능 비동기 이벤트 기반으로 변경
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/valid/OrderValidator.java
  order/order-controller/src/main/java/shop/woowasap/order/controller/OrderController.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/Order.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/OrderType.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderEventConsumer.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderUseCase.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/event/PayFailEvent.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/event/PaySuccessEvent.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/OrderIdResponse.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/event/PayFailEvent.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/event/StockSuccessEvent.java
  order/order-domain/src/test/java/shop/woowasap/order/domain/OrderTest.java
  order/order-repository/src/main/java/shop/woowasap/order/repository/entity/OrderEntity.java
  order/order-repository/src/main/java/shop/woowasap/order/repository/entity/OrderEntityType.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderEventService.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderEventServiceTest.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
Labels: ♻️ refactor

#203 feat: 현재 판매 중인 Product 는 수정 불가능
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/ProductModificationPermissionException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Product.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/product/ProductTest.java
  shop/shop-repository/src/test/java/shop/woowasap/shop/repository/ProductRepositoryImplTest.java
  shop/shop-repository/src/test/java/shop/woowasap/shop/repository/support/ProductFixture.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/CartServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductConnectorServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/CartFixture.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/ProductFixture.java
Labels: ✨ feature

#205 feat: 장바구니 상품 Response 에 상품의 남은 재고 추가
  app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/fixture/CartFixture.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/cart/response/CartProductResponse.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/mapper/CartMapper.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/CartFixture.java
Labels: ✨ feature

#206 refactor: order 모듈 `Instant.now() -> TimeUtil.now()` 로 변경
  order/order-service/build.gradle
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
Labels: ♻️ refactor

#202 feat: 결제 도메인 및 서비스 생성
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/event/PaySuccessEvent.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/event/PayFailEvent.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/event/StockSuccessEvent.java
  payment/payment-domain/build.gradle
  payment/payment-domain/src/main/java/shop/woowasap/payment/domain/PayStatus.java
  payment/payment-domain/src/main/java/shop/woowasap/payment/domain/Payment.java
  payment/payment-domain/src/main/java/shop/woowasap/payment/domain/exception/DoesNotFindPaymentException.java
  payment/payment-domain/src/main/java/shop/woowasap/payment/domain/exception/PayUserNotMatchException.java
  payment/payment-domain/src/main/java/shop/woowasap/payment/domain/in/PaymentUseCase.java
  payment/payment-domain/src/main/java/shop/woowasap/payment/domain/in/request/PaymentRequest.java
  payment/payment-domain/src/main/java/shop/woowasap/payment/domain/in/response/PaymentResponse.java
  payment/payment-domain/src/main/java/shop/woowasap/payment/domain/out/.gitkeep
  payment/payment-domain/src/main/java/shop/woowasap/payment/domain/out/PaymentRepository.java
  payment/payment-service/build.gradle
  payment/payment-service/src/main/java/shop/woowasap/payment/service/.gitkeep
  payment/payment-service/src/main/java/shop/woowasap/payment/service/PaymentEventService.java
  payment/payment-service/src/main/java/shop/woowasap/payment/service/PaymentService.java
  payment/payment-service/src/test/java/shop/woowasap/payment/service/PaymentEventServiceTest.java
  payment/payment-service/src/test/java/shop/woowasap/payment/service/PaymentServiceTest.java
Labels: ✨ feature

#208 refactor: CartProduct의 수량을 최소 1개 최대 10개로 설정
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/CartProduct.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/CartProductQuantity.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartProductTest.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartTest.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/support/CartFixture.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/CartService.java
Labels: ♻️ refactor

#209 feat: `OrderConnector` 인터페이스 구현
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderConnector.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderConnectorService.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderConnectorServiceTest.java
Labels: ✨ feature

#213 test: `Order` -> `Payment` 검증 테스트 추가
  app/build.gradle
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/PayOrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/PayApiSupporter.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/DetailOrderResponse.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderEventService.java
  order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java
  order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderDtoFixture.java
  payment/payment-repository/src/main/java/shop/woowasap/payment/repository/PaymentRepositoryImpl.java
  payment/payment-repository/src/main/java/shop/woowasap/payment/repository/jpa/PaymentEntityRepository.java
  payment/payment-repository/src/test/java/shop/woowasap/payment/repository/PaymentRepositoryImplTest.java
Labels: ✅ test

#215 feat: `Async thread, wait queue` count 설정
  app/build.gradle
  app/src/test/java/shop/woowasap/accept/PayOrderAcceptanceTest.java
  coverage-exclude.asap
  order/order-service/src/main/java/shop/woowasap/order/service/OrderEventService.java
  order/order-service/src/main/java/shop/woowasap/order/service/config/OrderAsyncConfig.java
  payment/payment-service/src/main/java/shop/woowasap/payment/service/PaymentEventService.java
  payment/payment-service/src/main/java/shop/woowasap/payment/service/config/PaymentAsyncConfig.java
Labels: ✨ feature

#216 feat: 상품 등록 시, 시간 검증 로직 구현
  app/build.gradle
  app/src/test/java/shop/woowasap/accept/AcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/CartAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/PayOrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/fixture/ProductFixture.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/OrderProduct.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
  order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderProductFixture.java
  order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/ProductFixture.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/InvalidProductSaleDurationException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/InvalidProductSaleTimeException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/InvalidProductStartTimeException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/out/ProductRepository.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Product.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/SaleTime.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartProductTest.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartTest.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/product/ProductTest.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/product/SaleTimeTest.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/support/CartFixture.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/support/DomainFixture.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/support/ProductFixture.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/ProductRepositoryImpl.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/entity/ProductEntity.java
  shop/shop-repository/src/test/java/shop/woowasap/shop/repository/CartRepositoryImplTest.java
  shop/shop-repository/src/test/java/shop/woowasap/shop/repository/ProductRepositoryImplTest.java
  shop/shop-repository/src/test/java/shop/woowasap/shop/repository/support/ProductFixture.java
  shop/shop-service/build.gradle
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/mapper/ProductMapper.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/ProductDtoFixture.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/ProductFixture.java
Labels: ✨ feature

#219 refactor: Clock 빈을 TimeUtil로 대체
  app/src/main/java/shop/woowasap/configuration/TimeConfiguration.java
  app/src/test/java/shop/woowasap/accept/AcceptanceTestConfiguration.java
  auth/auth-infra/build.gradle
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/JwtTokenProvider.java
  auth/auth-infra/src/test/java/shop/woowasap/auth/infra/JwtTokenProviderTest.java
Labels: ♻️ refactor

#221 chore: `Sentry Connect`
  app/build.gradle
  app/src/main/java/shop/woowasap/advice/GlobalExceptionHandler.java
  app/src/main/resources/application.yml
  app/src/main/resources/logback-spring.xml
  auth/auth-controller/src/main/java/shop/woowasap/auth/controller/AuthController.java
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/configuration/WebSecurityConfiguration.java
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/resolver/AuthArgumentResolver.java
  auth/auth-infra/src/test/java/shop/woowasap/auth/infra/AuthenticationProviderTest.java
  auth/auth-infra/src/test/java/shop/woowasap/auth/infra/JwtTokenProviderTest.java
  auth/auth-repository/src/test/java/shop/woowasap/auth/repository/UserRepositoryImplTest.java
  gradle.properties
  payment/payment-controller/src/main/java/shop/woowasap/payment/controller/PayController.java
Labels: 🍻 chore

#223 chore: `SENTRY_DSN` 변수 주입방식을 `jvm-args` 로 변경
  app/src/main/resources/application.yml
  app/src/main/resources/logback-spring.xml
  gradle.properties
Labels: 🍻 chore

#225 chore: 도커 이미지 빌드, workflow 추가
  .github/workflows/docker-image-build.yml
  Dockerfile
  app/build.gradle
Labels: 🍻 chore

#227 chore: 환경변수 설정 추가
  .github/workflows/docker-image-build.yml
  Dockerfile
Labels: 🍻 chore

#229 chore: Spring boot actuator와 모니터링 툴 부착
  app/build.gradle
  app/src/main/resources/application-prod.yml
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/configuration/WebSecurityConfiguration.java
Labels: 🍻 chore

#231 fix: docker-image build yml파일 수정
  .github/workflows/docker-image-build.yml
Labels: 🐛 bug-fix

#239 feat: `ErrorTemplate`, `ControllerAdvice` 를 부착
  app/src/main/java/shop/woowasap/advice/GlobalExceptionHandler.java
  auth/auth-controller/build.gradle
  auth/auth-controller/src/main/java/shop/woowasap/auth/controller/AuthController.java
  core/util/src/main/java/shop/woowasap/core/util/web/ErrorTemplate.java
  coverage-exclude.asap
  order/order-controller/build.gradle
  order/order-controller/src/main/java/shop/woowasap/order/controller/OrderController.java
  payment/payment-controller/build.gradle
  payment/payment-controller/src/main/java/shop/woowasap/payment/controller/PayController.java
  shop/shop-controller/build.gradle
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/CartController.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductAdminController.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java
Labels: ✨ feature

#240 chore: `4xx` 번 예외 info 로그 남기게 설정
  app/src/main/resources/logback-spring.xml
  auth/auth-controller/src/main/java/shop/woowasap/auth/controller/AuthController.java
  coverage-exclude.asap
  order/order-controller/src/main/java/shop/woowasap/order/controller/OrderController.java
  payment/payment-controller/src/main/java/shop/woowasap/payment/controller/PayController.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/CartController.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductAdminController.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java
Labels: 🍻 chore

#244 feat: 상품 판매 시간 변경
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/SaleTime.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/product/ProductTest.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/product/SaleTimeTest.java
  shop/shop-repository/src/test/java/shop/woowasap/shop/repository/support/ProductFixture.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/ProductFixture.java
Labels: ✨ feature

#247 feat: 예외 메시지를 추가
  payment/payment-domain/src/main/java/shop/woowasap/payment/domain/exception/DoesNotFindOrderException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/CartException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/InvalidProductDescriptionException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/InvalidProductNameException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/InvalidProductPriceException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/InvalidProductQuantityException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/InvalidProductSaleDurationException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/InvalidProductStartTimeException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/exception/ProductException.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Description.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Name.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Price.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Quantity.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/SaleTime.java
Labels: ✨ feature

#252 fix: CORS 패턴으로 수정
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/configuration/WebSecurityConfiguration.java
Labels: 🐛 bug-fix

#256 refactor: `Order`와 `Pay` `Transaction`을 비동기에서 동기로 바꾸고, 트랜잭션 레벨을 조절한다
  .gitignore
  app/build.gradle
  app/src/test/java/shop/woowasap/accept/PayOrderAcceptanceTest.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderConnector.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderEventConsumer.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/event/PayFailEvent.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/event/PaySuccessEvent.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/event/StockFailEvent.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/event/StockSuccessEvent.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderConnectorService.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderEventService.java
  order/order-service/src/main/java/shop/woowasap/order/service/config/OrderAsyncConfig.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderConnectorServiceTest.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderEventServiceTest.java
  payment/payment-service/src/main/java/shop/woowasap/payment/service/PaymentEventService.java
  payment/payment-service/src/main/java/shop/woowasap/payment/service/PaymentService.java
  payment/payment-service/src/main/java/shop/woowasap/payment/service/config/PaymentAsyncConfig.java
  payment/payment-service/src/test/java/shop/woowasap/payment/service/PaymentEventServiceTest.java
  payment/payment-service/src/test/java/shop/woowasap/payment/service/PaymentServiceTest.java
Labels: ♻️ refactor

#257 test: 주문취소 인수테스트 작성
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/OrderApiSupporter.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/OrderType.java
Labels: ✅ test

#258 feat: `Order` , `Pay` Cancel 서비스를 구현한다
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderUseCase.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/event/OrderCanceledEvent.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
  payment/payment-domain/src/main/java/shop/woowasap/payment/domain/out/PaymentRepository.java
  payment/payment-domain/src/test/java/shop/woowasap/payment/domain/PaymentTest.java
  payment/payment-domain/src/test/java/shop/woowasap/payment/domain/support/PaymentFixture.java
  payment/payment-repository/src/main/java/shop/woowasap/payment/repository/PaymentRepositoryImpl.java
  payment/payment-repository/src/main/java/shop/woowasap/payment/repository/jpa/PaymentEntityRepository.java
  payment/payment-repository/src/test/java/shop/woowasap/payment/repository/PaymentRepositoryImplTest.java
  payment/payment-service/src/main/java/shop/woowasap/payment/service/PaymentEventService.java
  payment/payment-service/src/main/java/shop/woowasap/payment/service/PaymentService.java
  payment/payment-service/src/test/java/shop/woowasap/payment/service/PaymentEventServiceTest.java
  payment/payment-service/src/test/java/shop/woowasap/payment/service/PaymentServiceTest.java
  payment/payment-service/src/test/java/shop/woowasap/payment/service/support/PaymentFixture.java
Labels: ✨ feature

#259 feat: `OrderController` 를 구현한다
  app/src/main/resources/db/migration/V2__update_order_type.sql
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/OrderApiSupporter.java
  order/order-controller/src/main/java/shop/woowasap/order/controller/OrderController.java
  order/order-repository/src/main/java/shop/woowasap/order/repository/entity/OrderEntityType.java
Labels: ✨ feature

#260 feat: `Order` 취소 기능 개발
  app/src/main/resources/db/migration/V2__update_order_type.sql
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/api/OrderApiSupporter.java
  order/order-controller/src/main/java/shop/woowasap/order/controller/OrderController.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/OrderType.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/OrderUseCase.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/out/event/OrderCanceledEvent.java
  order/order-repository/src/main/java/shop/woowasap/order/repository/entity/OrderEntityType.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderServiceTest.java
  payment/payment-domain/src/main/java/shop/woowasap/payment/domain/out/PaymentRepository.java
  payment/payment-domain/src/test/java/shop/woowasap/payment/domain/PaymentTest.java
  payment/payment-domain/src/test/java/shop/woowasap/payment/domain/support/PaymentFixture.java
  payment/payment-repository/src/main/java/shop/woowasap/payment/repository/PaymentRepositoryImpl.java
  payment/payment-repository/src/main/java/shop/woowasap/payment/repository/jpa/PaymentEntityRepository.java
  payment/payment-repository/src/test/java/shop/woowasap/payment/repository/PaymentRepositoryImplTest.java
  payment/payment-service/src/main/java/shop/woowasap/payment/service/PaymentEventService.java
  payment/payment-service/src/main/java/shop/woowasap/payment/service/PaymentService.java
  payment/payment-service/src/test/java/shop/woowasap/payment/service/PaymentEventServiceTest.java
  payment/payment-service/src/test/java/shop/woowasap/payment/service/PaymentServiceTest.java
  payment/payment-service/src/test/java/shop/woowasap/payment/service/support/PaymentFixture.java
Labels: ✨ feature

#267 refactor: `batchSize` 와 `default batchsize` 10으로 설정
  app/src/main/resources/application-dev.yml
  app/src/main/resources/application-prod.yml
  app/src/test/resources/application.yml
  order/order-repository/src/main/java/shop/woowasap/order/repository/entity/OrderEntity.java
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/entity/CartEntity.java
Labels: ♻️ refactor

#269 refactor: 재결제 로직 수정
  payment/payment-domain/src/main/java/shop/woowasap/payment/domain/in/response/PaymentResponse.java
  payment/payment-domain/src/main/java/shop/woowasap/payment/domain/out/PaymentRepository.java
  payment/payment-repository/src/main/java/shop/woowasap/payment/repository/PaymentRepositoryImpl.java
  payment/payment-repository/src/test/java/shop/woowasap/payment/repository/PaymentRepositoryImplTest.java
  payment/payment-service/src/main/java/shop/woowasap/payment/service/PaymentService.java
  payment/payment-service/src/test/java/shop/woowasap/payment/service/PaymentServiceTest.java
Labels: ♻️ refactor

#274 feat: 장바구니 주문 후, 장바구니 비우기
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderConnectorService.java
  order/order-service/src/test/java/shop/woowasap/order/service/OrderConnectorServiceTest.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/Cart.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/cart/CartConnector.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/cart/CartUseCase.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartTest.java
  shop/shop-repository/src/test/java/shop/woowasap/shop/repository/CartRepositoryImplTest.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/CartConnectorService.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/CartService.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/CartConnectorServiceTest.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/CartServiceTest.java
Labels: ✨ feature

#279 fix: check 제약 조건과 인덱스 설정
  app/src/main/resources/db/migration/V1__init.sql
  app/src/main/resources/db/migration/V2__index.sql
  shop/shop-repository/src/main/java/shop/woowasap/shop/repository/entity/ProductEntity.java
Labels: 🐛 bug-fix

#278 refactor: 주문 내역 리스트에서 OrderId 역순으로 정렬 및 주문 타입 추가
  app/src/test/java/shop/woowasap/accept/OrderAcceptanceTest.java
  order/order-domain/src/main/java/shop/woowasap/order/domain/in/response/OrderResponse.java
  order/order-repository/src/main/java/shop/woowasap/order/repository/OrderRepositoryImpl.java
  order/order-repository/src/test/java/shop/woowasap/order/repository/OrderRepositoryImplTest.java
  order/order-service/src/main/java/shop/woowasap/order/service/OrderService.java
  order/order-service/src/main/java/shop/woowasap/order/service/mapper/OrderMapper.java
  order/order-service/src/test/java/shop/woowasap/order/service/support/fixture/OrderDtoFixture.java
Labels: ♻️ refactor

#281 feat: cache 설정 추가
  app/build.gradle
  app/src/main/java/shop/woowasap/config/RedisConfig.java
  app/src/main/resources/application-dev.yml
  app/src/main/resources/application-prod.yml
  app/src/test/java/shop/woowasap/accept/AcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/AcceptanceTestConfiguration.java
  app/src/test/java/shop/woowasap/accept/ProductAcceptanceTest.java
  app/src/test/java/shop/woowasap/accept/support/fixture/ProductFixture.java
  app/src/test/resources/application.yml
  auth/auth-infra/src/main/java/shop/woowasap/auth/infra/configuration/WebSecurityConfiguration.java
  shop/shop-controller/src/main/java/shop/woowasap/shop/controller/ProductController.java
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/in/product/response/ProductResponse.java
  shop/shop-service/build.gradle
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/config/ShopCacheConfig.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/mapper/ProductMapper.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/support/fixture/ProductFixture.java
Labels: ✨ feature

#282 fix: gradle build action 버전 수정
  .github/workflows/deploy.yml
  .github/workflows/docker-image-build.yml
Labels: 🐛 bug-fix

#285 fix: `consume stock`에서 `DoesNotOrderedException` 롤백 방지
  order/order-service/src/main/java/shop/woowasap/order/service/OrderConnectorService.java
Labels: 🐛 bug-fix

#288 fix: Product의 재고가 0인 경우, Cart에 담기는 경우 예외처리 추가
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/cart/CartProductQuantity.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/cart/CartProductTest.java
Labels: 🐛 bug-fix

#292 fix: 상품 수정 요청 시, startTime 과 endTime 검증 로직 추가
  shop/shop-domain/src/main/java/shop/woowasap/shop/domain/product/Product.java
  shop/shop-domain/src/test/java/shop/woowasap/shop/domain/product/ProductTest.java
  shop/shop-repository/src/test/java/shop/woowasap/shop/repository/ProductRepositoryImplTest.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
  shop/shop-service/src/main/java/shop/woowasap/shop/service/mapper/ProductMapper.java
  shop/shop-service/src/test/java/shop/woowasap/shop/service/ProductServiceTest.java
Labels: 🐛 bug-fix

#290 feat: 상품이 등록되거나 수정될 때 Redis Cache 초기화
  shop/shop-service/src/main/java/shop/woowasap/shop/service/ProductService.java
Labels: ✨ feature

#295 docs: `Readme.md` 작성
  README.md
Labels: 📝 docs
